- name: Update apt
  apt:
    update_cache: yes

- name: Install Node.js and npm
  apt:
    name: [nodejs, npm]
    state: present

- name: Copy app files
  copy:
    src: files/your-app-code/
    dest: /home/ubuntu/app/
    owner: ubuntu
    group: ubuntu
    mode: 0755

- name: Install npm dependencies
  command: npm install
  args:
    chdir: /home/ubuntu/app/

- name: Create systemd service
  template:
    src: app.service.j2
    dest: /etc/systemd/system/app.service

- name: Reload systemd and enable service
  systemd:
    name: app
    daemon_reload: yes
    enabled: yes
    state: started